---
- name: Pre-install stuff
  hosts: all
  tasks:
    - name: Install python 2 if not there
      raw: |
        test -e /usr/bin/python || \
        (apt -y update && apt install -y  python-minimal)
      register: output
      changed_when: output.stdout|trim() != ""
    - name: Install sudo if not there
      raw: |
        test -e /usr/bin/sudo || apt install -y sudo
      register: output
      changed_when: output.stdout|trim() != ""
  gather_facts: False
  become: True

- name: Run mosh role (setup a computer like mosh does)
  hosts: all
  gather_facts: True
  become: True
  roles:
    - role: roles/mosh
