---
- name: Pre-install stuff
  hosts: localhost
  connection: local
  tasks:
    - name: Install sudo if not there
      raw: |
        test -e /usr/bin/sudo || apt install -y sudo
      register: output
      changed_when: output.stdout|trim() != ""
  gather_facts: False
  become: True

- name: Run mosh role (setup a computer like mosh does)
  hosts: localhost
  connection: local
  gather_facts: True
  become: True
  roles:
    - role: roles/mosh
