---
- name: Determine fish shell executable location
  command: which fish
  register: fish

- name: Set fish as the default shell
  user:
    name: '{{ mosh_system_user }}'
    shell: '{{ fish.stdout }}'
  become: yes
