---
- name: Install python
  include_tasks: install/python.yml
  tags:
    - install
    - lang
    - python
  when:
    - mosh_install_python == true

- name: Configure python
  include_tasks: configure/python.yml
  tags:
    - configure
    - lang
    - python
  when:
    - mosh_install_python == true

- name: Install fish
  include_tasks: install/fish.yml
  tags:
    - install
    - shell
    - fish
  when:
    - mosh_install_fish == true

- name: Configure fish
  include_tasks: configure/fish.yml
  tags:
    - configure
    - shell
    - fish
  when:
    - mosh_install_fish == true

- name: Configure git
  include_tasks: configure/git.yml
  tags:
    - configure
    - dotfiles
    - git
